alternate: Angtian Wang

statics: /

loader:
  start: true # 当初次打开页面时，显示加载动画
  switch: false # tab 切换到其他页面时，显示加载动画

social:
  github: https://github.com/Angtian || github || "#191717"
  email: angtianwang@gmail.com || envelope || "#55acd5"
#  facebook: https://www.facebook.com/yourname || facebook
  #google: https://plus.google.com/yourname || google
#  twitter: https://twitter.com/amehime || twitter || "#00aff0"
#  zhihu: https://www.zhihu.com/people/rurismzk || zhihu || "#1e88e5"
#  music: https://music.163.com/#/user/home?id=12886823 || cloud-music || "#e60026"
#  weibo: https://weibo.com/amehime || weibo || "#ea716e"
#  about: https://about.me/amehime || address-card || "#3b5998"

menu:
  home: / || home

exturl: true

